---
satellite_server_url: https://satellite.domain.com
satellite_username: admin
satellite_password: somepassword
satellite_validate_certs: false
ldap_account: DOMAIN\someaccount
ldap_password: somepassword
